@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueAffiliationList
UniqueAffiliationList -[hidden]down- UniquePersonList
UniqueAffiliationList -[hidden]down- UniquePersonList

UniqueAffiliationList -right-> "*" Affiliation
UniquePersonList -right-> Person

Person -up-> "*" Affiliation

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
@enduml
